name: MacOS CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Gather pre-requisites
      run: brew install ninja libtool automake cmake pkg-config gettext
    - name: Attempt to build neovim
      run: |
        echo Making project...,
        make CMAKE_BUILD_TYPE=RelWithDebInfo
