name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Attempt to build neovim
      run: sudo port install ninja libtool autoconf automake cmake pkgconfig gettext
  
