name: Ubuntu CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Gather pre-requisites
      run: sudo apt-get install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
    - name: Attempt to build NeoVim
      run: |
        echo Making project...,
        make CMAKE_BUILD_TYPE=RelWithDebInfo
    - name: Run automated testing
      run: |
        echo Running first test, open TODO with no notes,
        nvim -c todo
